[package]
name = "termion"
version = "2.0.1"
authors = [
    "ticki <Ticki@users.noreply.github.com>",
    "gycos <alexandre.bury@gmail.com>",
    "IGI-111 <igi-111@protonmail.com>",
    "Jeremy Soller <jackpot51@gmail.com>",
]
description = "A bindless library for manipulating terminals."
repository = "https://gitlab.redox-os.org/redox-os/termion"
documentation = "https://docs.rs/termion"
license = "MIT"
keywords = ["tty", "color", "terminal", "password", "tui"]
exclude = ["target", "CHANGELOG.md", "image.png", "Cargo.lock"]

[dependencies]
numtoa = { version = "0.1", features = ["std"]}
serde = { version = "1.0", features = ["derive"], optional = true }

[target.'cfg(all(not(target_os = "redox"), not(windows)))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
redox_termios = "0.1" 

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.6.1"
